import { normaliseHeadword } from "../dictionary/format";

// RL-37: the translation a reader expects for a function word, which the
// dictionary orders by its own corpus and so often puts a rare sense first.
// Hand-written device data, never fetched: the phrase fallback stays offline.
// Chosen from SUBTLEX-US by frequency among pronouns, determiners,
// prepositions, conjunctions, auxiliaries and the commonest adverbs of
// position and degree; one or two glosses, the common sense first.
const ENTRIES: ReadonlyArray<readonly [string, string]> = [
  // pronouns
  ["i", "yo"],
  ["you", "tú, usted"],
  ["he", "él"],
  ["she", "ella"],
  ["it", "eso, lo"],
  ["we", "nosotros"],
  ["they", "ellos, ellas"],
  ["me", "me, mí"],
  ["him", "lo, él"],
  ["her", "su, la"],
  ["us", "nos, nosotros"],
  ["them", "los, ellos"],
  ["my", "mi"],
  ["your", "tu, su"],
  ["his", "su"],
  ["our", "nuestro"],
  ["their", "su, de ellos"],
  ["this", "esto, este"],
  ["that", "eso, que"],
  ["these", "estos"],
  ["those", "esos, aquellos"],
  ["who", "quién"],
  ["what", "qué, lo que"],
  ["which", "cuál, que"],
  ["where", "dónde"],
  ["when", "cuándo, cuando"],
  ["why", "por qué"],
  ["how", "cómo"],
  ["someone", "alguien"],
  ["something", "algo, alguna cosa"],
  ["anything", "algo, cualquier cosa"],
  ["nothing", "nada"],
  ["nobody", "nadie"],
  ["everyone", "todos"],
  ["everything", "todo"],
  // determiners and quantifiers
  ["the", "el, la"],
  ["a", "un, una"],
  ["some", "unos, algo de"],
  ["any", "algún, cualquier"],
  ["no", "no, ningún"],
  ["all", "todo, todos"],
  ["every", "cada"],
  ["many", "muchos"],
  ["more", "más"],
  ["most", "la mayoría, más"],
  ["other", "otro"],
  ["one", "uno, un"],
  // prepositions
  ["of", "de"],
  ["to", "a, para"],
  ["in", "en"],
  ["on", "en, sobre"],
  ["at", "en, a"],
  ["for", "para, por"],
  ["with", "con"],
  ["from", "de, desde"],
  ["by", "por, junto a"],
  ["about", "sobre, acerca de"],
  ["into", "dentro de, hacia"],
  ["over", "sobre, encima de"],
  ["after", "después de, después"],
  ["before", "antes de, antes"],
  ["under", "bajo, debajo de"],
  ["without", "sin"],
  ["as", "como"],
  ["than", "que"],
  // conjunctions
  ["and", "y"],
  ["but", "pero"],
  ["or", "o"],
  ["so", "así que, tan"],
  ["if", "si"],
  ["because", "porque"],
  ["then", "entonces"],
  // auxiliaries and modals
  ["be", "ser, estar"],
  ["am", "soy, estoy"],
  ["is", "es, está"],
  ["are", "son, están"],
  ["was", "era, fue"],
  ["were", "eran, fueron"],
  ["have", "tener, haber"],
  ["has", "tiene, ha"],
  ["had", "tenía, había"],
  ["do", "hacer"],
  ["does", "hace"],
  ["did", "hizo"],
  ["will", "(futuro)"],
  ["would", "(condicional)"],
  ["can", "poder"],
  ["could", "podría"],
  ["should", "debería"],
  ["must", "deber, tener que"],
  // adverbs of position, degree and time
  ["not", "no"],
  ["just", "solo, justo"],
  ["now", "ahora"],
  ["here", "aquí"],
  ["there", "allí, hay"],
  ["very", "muy"],
  ["too", "también, demasiado"],
  ["also", "también"],
  ["only", "solo, único"],
  ["even", "incluso, aun"],
  ["still", "todavía, aún"],
  ["again", "otra vez, de nuevo"],
  ["never", "nunca"],
  ["always", "siempre"],
  ["already", "ya"],
  ["maybe", "quizás, tal vez"],
  ["really", "de verdad, realmente"],
  ["up", "arriba"],
  ["down", "abajo"],
  ["out", "fuera, afuera"],
];

export const FUNCTION_WORDS: ReadonlyMap<string, string> = new Map(
  ENTRIES.map(([word, translation]) => [normaliseHeadword(word), translation]),
);

export function functionWordTranslation(token: string): string | null {
  return FUNCTION_WORDS.get(normaliseHeadword(token)) ?? null;
}
